const KEY="indoFlashcards400";
const defaults={activeUnit:1,completed:[],mastered:[],words:{}};
let state=load(), introFlipped=false, mode="intro", current=null;
const unitWords=u=>WORDS.filter(w=>w.rank>(u-1)*100&&w.rank<=u*100);
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}"),words:{...defaults.words,...(JSON.parse(localStorage.getItem(KEY)||"{}").words||{})}}}catch{return {...defaults}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function getInfo(rank){return state.words[rank]||{introduced:false,cycles:0,direction:"indo"}}
function setInfo(rank,x){state.words[rank]={...getInfo(rank),...x};save()}
function mastered(u){return unitWords(u).filter(w=>state.mastered.includes(w.rank)).length}
function deck(u){return unitWords(u).filter(w=>!state.mastered.includes(w.rank)&&getInfo(w.rank).introduced)}
function nextCard(){let d=deck(state.activeUnit);current=d[0]||null; if(!current){let fresh=unitWords(state.activeUnit).find(w=>!getInfo(w.rank).introduced&&!state.mastered.includes(w.rank)); if(fresh){current=fresh;mode="intro"} else if(mastered(state.activeUnit)>=100){completeUnit();return}else{current=d[0]||null}} render()}
function completeUnit(){if(!state.completed.includes(state.activeUnit))state.completed.push(state.activeUnit);if(state.activeUnit<4)state.activeUnit++;save();current=unitWords(state.activeUnit).find(w=>!state.mastered.includes(w.rank));mode=current?"intro":"typing";render()}
function render(){renderNav();const u=state.activeUnit, m=mastered(u);document.getElementById("unitTitle").textContent=`Unit ${u} - ${u===1?"Most frequent":`Ranks ${(u-1)*100+1}-${u*100}`} - #${(u-1)*100+1}-${u*100}`;document.getElementById("progress").textContent=`${m}/100 mastered`;const card=document.getElementById("card"),controls=document.getElementById("controls");if(!current){nextCard();return} if(mode==="intro"){card.className="card flip "+(introFlipped?"flipped":"");card.innerHTML=`<div class="face front"><small>#${current.rank}</small><strong>${current.indo}</strong><span>Tap to flip</span></div><div class="face back"><small>#${current.rank} · English</small><strong>${current.en}</strong><span>Tap to flip back</span></div>`;controls.innerHTML=`<button id="flip">Flip</button><button id="next">Next</button>`;document.getElementById("flip").onclick=()=>{introFlipped=!introFlipped;render()};document.getElementById("next").onclick=()=>{setInfo(current.rank,{introduced:true});mode="typing";introFlipped=false;render()}}else{const info=getInfo(current.rank), prompt=info.direction==="indo"?current.indo:current.en;card.className="card";card.innerHTML=`<small>#${current.rank}</small><strong>${prompt}</strong><span>Cycle ${info.cycles}/3 · ${info.direction==="indo"?"Indonesian → English":"English → Indonesian"}</span>`;controls.innerHTML=`<form id="answer"><input id="input" autocomplete="off" autocapitalize="none" placeholder="Type your answer"><button>Check</button></form><div id="feedback"></div>`;document.getElementById("input").focus();document.getElementById("answer").onsubmit=e=>{e.preventDefault();answer(document.getElementById("input").value)}}renderUnits();renderDictionary()}
function answer(raw){const info=getInfo(current.rank), expected=info.direction==="indo"?current.en:current.indo, ok=raw.trim().toLocaleLowerCase()===expected.toLocaleLowerCase(), fb=document.getElementById("feedback");if(ok){let cycles=info.cycles, dir=info.direction==="indo"?"en":"indo";if(info.direction==="en")cycles++;if(cycles>=3){state.mastered.push(current.rank);delete state.words[current.rank];fb.className="correct";fb.textContent="Correct — mastered!";save();setTimeout(()=>{current=null;nextCard()},500);return}setInfo(current.rank,{cycles,direction:dir});fb.className="correct";fb.textContent="Correct!";current=null;setTimeout(()=>{current=deck(state.activeUnit)[0];render()},450)}else{fb.className="wrong";fb.innerHTML=`Correct answer: <strong>${expected}</strong>`;setInfo(current.rank,{cycles:0,direction:"indo"});current=null;setTimeout(()=>{current=deck(state.activeUnit)[0];render()},900)}}
function renderNav(){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view==="study"));document.querySelectorAll(".view").forEach(v=>v.classList.toggle("hidden",v.id!=="study"))}
function renderUnits(){const el=document.getElementById("unitsList");if(!el)return;el.innerHTML=[1,2,3,4].map(u=>`<div class="unit"><div><b>Unit ${u}</b><span>Ranks #${(u-1)*100+1}-${u*100}${u===1?" · Most frequent":""}</span></div><button data-u="${u}">${state.completed.includes(u)?"Review":"Study"} · ${mastered(u)}/100</button></div>`).join("");el.querySelectorAll("button").forEach(b=>b.onclick=()=>reviewUnit(+b.dataset.u))}
function reviewUnit(u){state.activeUnit=u;const w=unitWords(u).find(x=>state.mastered.includes(x.rank));if(!w){nextCard();return}current=w;mode="review";renderReview()}
function renderReview(){const u=state.activeUnit;document.querySelectorAll(".view").forEach(v=>v.classList.toggle("hidden",v.id!=="study"));const w=current;const card=document.getElementById("card");card.className="card flip";card.innerHTML=`<div class="face front"><small>#${w.rank}</small><strong>${w.indo}</strong><span>Tap to flip</span></div><div class="face back"><small>#${w.rank} · English</small><strong>${w.en}</strong></div>`;document.getElementById("controls").innerHTML=`<button id="flip">Flip</button><button id="backUnits">Back to Units</button>`;document.getElementById("flip").onclick=()=>card.classList.toggle("flipped");document.getElementById("backUnits").onclick=()=>show("units")}
function renderDictionary(){const q=(document.getElementById("search")?.value||"").toLowerCase();const el=document.getElementById("dictionaryList");if(!el)return;const arr=WORDS.filter(w=>state.mastered.includes(w.rank)&&(!q||w.indo.toLowerCase().includes(q)||w.en.toLowerCase().includes(q)));el.innerHTML=arr.length?arr.map(w=>`<div class="entry"><b>#${w.rank} · ${w.indo}</b><span>${w.en}</span></div>`).join(""):"<p class='empty'>Your dictionary is empty. Master words to add them.</p>"}
function show(v){document.querySelectorAll(".view").forEach(x=>x.classList.toggle("hidden",x.id!==v));document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(v==="units")renderUnits();if(v==="dictionary")renderDictionary()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));document.getElementById("card").onclick=()=>{if(mode==="intro"||mode==="review"){introFlipped=!introFlipped;document.getElementById("card").classList.toggle("flipped",introFlipped)}};document.getElementById("search").oninput=renderDictionary;document.getElementById("reset").onclick=()=>{if(confirm("Reset all progress?")){localStorage.removeItem(KEY);location.reload()}};nextCard();